id: hl7.fhir.us.shrae
canonical: http://hl7.org/fhir/us/shrae
version: 0.0.1
name: HL7FHIRImplementationGuideStandardHealthRecordAdverseEventsRelease1USRealmSTU1
title: "HL7 FHIR Implementation Guide: Standard Health Record (SHR) Adverse Events
  Release 1 - DRAFT"
status: draft
publisher:
  name: HL7 International Clinical Interoperability Council
  url: http://www.mcodeinitiative.org
jurisdiction: urn:iso:std:iso:3166#US "United States of America"
description: The Standard Health Record (SHR) Adverse Event specification reconciles CTCAE and CDISC CDASH.
license: CC0-1.0
fhirVersion: 4.0.1
dependencies:
  hl7.fhir.us.core: 3.1.0
  hl7.fhir.us.mcode: 1.16.0
parameters:
  show-inherited-invariants: false
  version-comparison: n/a
  path-expansion-params: '../../exp-params.json'  #path is relative to [base]/fsh-generated/resources
copyrightYear: 2021+
releaseLabel: DRAFT
pages:
  index.md:
    title: Home
  implementation.md:
    title: Implementation
  examples.md:
    title: Examples Overview
  examplepersona1.md:
    title: Persona 1 - Clinical Trials Patient
  examplepersona2.md:
    title: Persona 2 - Standard of Care Patient
  downloads.md:
    title: Downloads
  change_log.md:
    title: Change log
menu:
  Home: index.html
  Implementation: implementation.html
  Extended Examples: examples.html
  FHIR Artifacts:
    Profiles: "artifacts.html#1"
    Extensions: "artifacts.html#2"
    ValueSets: "artifacts.html#3"
    CodeSystems: "artifacts.html#4"
    GenericExamples: "artifacts.html#5"
    All artifacts: "artifacts.html"
  Downloads: downloads.html
  Change Log: change_log.html
  History: http://hl7.org/fhir/us/shrae/history.html

groups:
  Profiles:
    name: Profiles
    description: Adverse event related profiles
    resources:
      - StructureDefinition/ctc-adverse-event
      - StructureDefinition/ae-patient-bundle

  # Extensions
  Extensions:
    name: Extensions
    description: These define AE extensions to some of the above profiles.
    resources:
      - StructureDefinition/adverse-event-expectation
      - StructureDefinition/adverse-event-resolved-date
      - StructureDefinition/ctcae-grade

  # Value sets
  ValueSets:
    name: Value Sets
    description: These define sets of codes used by systems conforming with this implementation guide. Comorbid condition-related value sets appear in a separate section below.
    resources:
      - ValueSet/ctcae-term-value-set
      - ValueSet/adverse-event-expectation-value-set
      - ValueSet/adverse-event-seriousness-value-set
      - ValueSet/adverse-event-relatedness-value-set
      - ValueSet/ctcae-grade-value-set

  CodeSystems:
    name: Code Systems
    description: These define new code systems used by systems conforming with this implementation guide
    resources:
      - CodeSystem/ctcae-grade-code-system

  CTCAESpecificExamples:
    name: "CTCAE examples"
    description: "Examples of resources conforming to a CTCAE AdverseEvent profile."
    resources:
      - AdverseEvent/ctc-adverse-event-example-1
      - AdverseEvent/ctc-adverse-event-example-2
  
  GenericExamples:
    name: "Examples:"
    description: Examples of resources from other profiles (e.g. mCODE) or FHIR core resources which support the persona. These examples are independent (i.e., there is no expectation of consistency of data among the resources).
    resources:
      - Patient/patient-example-kaitlyn-b
      - Patient/PatientPersona2
      - Practitioner/PractitionerExample1
